### ISSUE TITLE
解釋 db.sequelize.sync() 

### ISSUE THREAD

**Issue by tsungtingdu** [zongronghuang/restaurant_forum#1]
https://github.com/zongronghuang/restaurant_forum/blob/647789188ce157e988c0ebebb4a5728ce8ce16c1/app.js#L50

路過看到註解， `db.sequelize.sync() ` 主要並不是確認與資料庫連線是否正常，它具有同步 model 與資料庫 schema 的作用，但也因此會造成問題，可以參考 [延伸閱讀](https://medium.com/@smallbee/how-to-use-sequelize-sync-without-difficulties-4645a8d96841) 的說明，特別是 **Some problems you might face after using ‘sync()’** 這段

**Comment by zongronghuang** [comment]
謝謝 Tim! 已經修改 comment :)
